# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportLights' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportLights

    pod 'Parse'

  target 'SportLightsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SportLightsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
